# Generated by Django 5.0.6 on 2024-06-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_article_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
